# Generated by Django 4.2.6 on 2023-11-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("praca_", "0002_create_post_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Literature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_book", models.CharField(max_length=150)),
                ("publishing_house", models.CharField(max_length=150)),
                ("year_release", models.PositiveIntegerField()),
            ],
        ),
    ]
