# Generated by Django 4.2.6 on 2023-11-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("praca_", "0003_create_literature_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="literature",
            name="post",
            field=models.ManyToManyField(to="praca_.post"),
        ),
    ]
